import { useState } from "react";

function DomainSearch() {
  const [domain, setDomain] = useState("");
    const [searched, setSearched] = useState(false);

      const handleSearch = (e) => {
          e.preventDefault();

              if (!domain.trim()) return;

                  setSearched(true);
                    };

                      return (
                          <section className="bg-slate-900 text-white py-20">
                                <div className="max-w-4xl mx-auto px-6 text-center">

                                        <h2 className="text-3xl md:text-4xl font-bold">
                                                  Find Your Perfect Domain
                                                          </h2>

                                                                  <p className="mt-4 text-slate-400">
                                                                            Search for a domain and start building your online presence.
                                                                                    </p>

                                                                                            <form
                                                                                                      onSubmit={handleSearch}
                                                                                                                className="mt-8 flex flex-col sm:flex-row gap-3"
                                                                                                                        >
                                                                                                                                  <div className="flex-1 flex items-center bg-slate-950 border border-slate-700 rounded-xl px-4">
                                                                                                                                              <span className="text-slate-400 mr-3">🔍</span>

                                                                                                                                                          <input
                                                                                                                                                                        type="text"
                                                                                                                                                                                      placeholder="yourdomain.com"
                                                                                                                                                                                                    value={domain}
                                                                                                                                                                                                                  onChange={(e) => setDomain(e.target.value)}
                                                                                                                                                                                                                                className="w-full bg-transparent outline-none py-4 text-white"
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                        className="bg-cyan-500 hover:bg-cyan-600 px-7 py-4 rounded-xl font-semibold transition"
                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                              Search
                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                        <div className="mt-6 flex justify-center gap-4 flex-wrap text-sm">
                                                                                                                                                                                                                                                                                                                                                  <span className="text-cyan-400">.com</span>
                                                                                                                                                                                                                                                                                                                                                            <span className="text-cyan-400">.net</span>
                                                                                                                                                                                                                                                                                                                                                                      <span className="text-cyan-400">.org</span>
                                                                                                                                                                                                                                                                                                                                                                                <span className="text-cyan-400">.dev</span>
                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-cyan-400">.co.ke</span>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                          {searched && (
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-8 bg-slate-950 border border-slate-700 rounded-xl p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                              🔍 Searching for{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-cyan-400 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {domain}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-2 text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Domain availability checking will be connected later 🚀
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default DomainSearch;