import { useState } from "react";

const faqs = [
  {
      question: "What is GwijiHost?",
          answer:
                "GwijiHost is a platform designed to make domains and website hosting simple and affordable for everyone.",
                  },
                    {
                        question: "Can I start hosting for free?",
                            answer:
                                  "Yes. GwijiHost will offer a free hosting option for users who want to start small before upgrading.",
                                    },
                                      {
                                          question: "Do you provide SSL certificates?",
                                              answer:
                                                    "Yes. Free SSL is included with supported hosting plans to help keep your website secure.",
                                                      },
                                                        {
                                                            question: "Can I register a domain through GwijiHost?",
                                                                answer:
                                                                      "Yes. Domain registration will be available through our domain registration system once the platform is connected to a real registrar.",
                                                                        },
                                                                          {
                                                                              question: "Can I upgrade my hosting plan later?",
                                                                                  answer:
                                                                                        "Absolutely. You will be able to upgrade as your website grows and needs more resources.",
                                                                                          },
                                                                                            {
                                                                                                question: "Do you provide customer support?",
                                                                                                    answer:
                                                                                                          "Yes. GwijiHost will provide customer support to help users with their hosting and domain services.",
                                                                                                            },
                                                                                                            ];

                                                                                                            function FAQ() {
                                                                                                              const [openIndex, setOpenIndex] = useState(null);

                                                                                                                const toggleFAQ = (index) => {
                                                                                                                    setOpenIndex(openIndex === index ? null : index);
                                                                                                                      };

                                                                                                                        return (
                                                                                                                            <section className="bg-slate-900 text-white py-20">
                                                                                                                                  <div className="max-w-4xl mx-auto px-6">

                                                                                                                                          <div className="text-center">
                                                                                                                                                    <h2 className="text-3xl md:text-4xl font-bold">
                                                                                                                                                                Frequently Asked Questions
                                                                                                                                                                          </h2>

                                                                                                                                                                                    <p className="mt-4 text-slate-400">
                                                                                                                                                                                                Everything you need to know about GwijiHost.
                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                          <div className="mt-12 space-y-4">
                                                                                                                                                                                                                                    {faqs.map((faq, index) => (
                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                              key={faq.question}
                                                                                                                                                                                                                                                                            className="border border-slate-800 rounded-xl overflow-hidden bg-slate-950"
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                      onClick={() => toggleFAQ(index)}
                                                                                                                                                                                                                                                                                                                                      className="w-full flex items-center justify-between text-left px-6 py-5 hover:bg-slate-900 transition"
                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                    <span className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                      {faq.question}
                                                                                                                                                                                                                                                                                                                                                                                                      </span>

                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-cyan-400 text-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                        {openIndex === index ? "−" : "+"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {openIndex === index && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="px-6 pb-5 text-slate-400 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {faq.answer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default FAQ;