const plans = [
      {
          name: "Free",
              price: "$0",
                  description: "Perfect for personal projects and beginners.",
                      features: [
                            "1 Website",
                                  "1 GB Storage",
                                        "Free SSL",
                                              "1 GB Bandwidth",
                                                  ],
                                                      button: "Start Free",
                                                        },
                                                          {
                                                              name: "Starter",
                                                                  price: "$2.99",
                                                                      description: "Everything you need to launch your first website.",
                                                                          features: [
                                                                                "5 Websites",
                                                                                      "10 GB SSD Storage",
                                                                                            "Free SSL",
                                                                                                  "50 GB Bandwidth",
                                                                                                      ],
                                                                                                          button: "Get Started",
                                                                                                            },
                                                                                                              {
                                                                                                                  name: "Pro",
                                                                                                                      price: "$5.99",
                                                                                                                          description: "Powerful hosting for growing websites.",
                                                                                                                              features: [
                                                                                                                                    "Unlimited Websites",
                                                                                                                                          "50 GB SSD Storage",
                                                                                                                                                "Free SSL",
                                                                                                                                                      "Unlimited Bandwidth",
                                                                                                                                                          ],
                                                                                                                                                              button: "Choose Pro",
                                                                                                                                                                  popular: true,
                                                                                                                                                                    },
                                                                                                                                                                    ];

                                                                                                                                                                    function HostingPlans() {
                                                                                                                                                                      return (
                                                                                                                                                                          <section id="pricing" className="bg-slate-950 text-white py-20">
                                                                                                                                                                                <div className="max-w-7xl mx-auto px-6">

                                                                                                                                                                                        <div className="text-center">
                                                                                                                                                                                                  <h2 className="text-3xl md:text-4xl font-bold">
                                                                                                                                                                                                              Hosting Plans
                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                  <p className="mt-4 text-slate-400">
                                                                                                                                                                                                                                              Simple, affordable hosting for everyone.
                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                        <div className="mt-12 grid md:grid-cols-3 gap-8">

                                                                                                                                                                                                                                                                                  {plans.map((plan) => (
                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                            key={plan.name}
                                                                                                                                                                                                                                                                                                                          className={`relative rounded-2xl border p-8 ${
                                                                                                                                                                                                                                                                                                                                          plan.popular
                                                                                                                                                                                                                                                                                                                                                            ? "border-cyan-400 bg-slate-900"
                                                                                                                                                                                                                                                                                                                                                                              : "border-slate-800 bg-slate-900/50"
                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                        >

                                                                                                                                                                                                                                                                                                                                                                                                                      {plan.popular && (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="absolute -top-3 left-1/2 -translate-x-1/2 bg-cyan-500 text-white px-4 py-1 rounded-full text-sm font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Most Popular
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {plan.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-3 text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {plan.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-4xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {plan.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {plan.price !== "$0" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /month
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="mt-8 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {plan.features.map((feature) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key={feature}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="flex items-center gap-3 text-slate-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-cyan-400">✓</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {feature}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`w-full mt-8 py-3 rounded-xl font-semibold transition ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      plan.popular
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "bg-cyan-500 hover:bg-cyan-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "border border-slate-700 hover:border-cyan-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {plan.button}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default HostingPlans;