import { Link } from "react-router-dom";

function Navbar() {
  return (
      <nav className="bg-slate-950 text-white border-b border-slate-800 sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-6">
                    <div className="h-20 flex items-center justify-between">

                              {/* Logo */}
                                        <Link to="/" className="flex items-center gap-3 group">
                                                    <div className="w-11 h-11 rounded-xl bg-cyan-500 flex items-center justify-center shadow-lg shadow-cyan-500/20 group-hover:scale-105 transition">
                                                                  <span className="text-slate-950 font-black text-xl">
                                                                                  G
                                                                                                </span>
                                                                                                            </div>

                                                                                                                        <div>
                                                                                                                                      <div className="text-xl font-extrabold tracking-tight">
                                                                                                                                                      Gwiji<span className="text-cyan-400">Host</span>
                                                                                                                                                                    </div>

                                                                                                                                                                                  <div className="text-[10px] uppercase tracking-[0.2em] text-slate-500">
                                                                                                                                                                                                  Hosting made simple
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                {/* Navigation */}
                                                                                                                                                                                                                                                          <div className="hidden md:flex items-center gap-8">

                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                    href="#hosting"
                                                                                                                                                                                                                                                                                                  className="text-sm font-medium text-slate-300 hover:text-cyan-400 transition"
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                            Hosting
                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                  href="#features"
                                                                                                                                                                                                                                                                                                                                                                                className="text-sm font-medium text-slate-300 hover:text-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                          Features
                                                                                                                                                                                                                                                                                                                                                                                                                      </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                href="#pricing"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="text-sm font-medium text-slate-300 hover:text-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Pricing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="#faq"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-sm font-medium text-slate-300 hover:text-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FAQ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-6 w-px bg-slate-800" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        to="/login"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-sm font-semibold text-slate-200 hover:text-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to="/register"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-cyan-500 hover:bg-cyan-400 text-slate-950 px-5 py-2.5 rounded-xl text-sm font-bold shadow-lg shadow-cyan-500/20 transition hover:-translate-y-0.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Get Started
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Navbar;