const testimonials = [
      {
          name: "Brian Mwangi",
              role: "Web Developer",
                  avatar: "BM",
                      message:
                            "GwijiHost made it incredibly easy to get my project online. The setup was simple and the hosting is fast.",
                              },
                                {
                                    name: "Aisha Hassan",
                                        role: "Small Business Owner",
                                            avatar: "AH",
                                                message:
                                                      "I love how simple GwijiHost is. I didn't need to understand complicated hosting settings to launch my website.",
                                                        },
                                                          {
                                                              name: "Kevin Otieno",
                                                                  role: "Freelancer",
                                                                      avatar: "KO",
                                                                          message:
                                                                                "The pricing is straightforward and the platform feels really easy to use. Definitely a great option for developers.",
                                                                                  },
                                                                                  ];

                                                                                  function Testimonials() {
                                                                                    return (
                                                                                        <section className="bg-slate-950 text-white py-20">
                                                                                              <div className="max-w-7xl mx-auto px-6">

                                                                                                      <div className="text-center">
                                                                                                                <h2 className="text-3xl md:text-4xl font-bold">
                                                                                                                            What Our Customers Say
                                                                                                                                      </h2>

                                                                                                                                                <p className="mt-4 text-slate-400">
                                                                                                                                                            Real experiences from people building online with GwijiHost.
                                                                                                                                                                      </p>
                                                                                                                                                                              </div>

                                                                                                                                                                                      <div className="mt-12 grid md:grid-cols-3 gap-8">
                                                                                                                                                                                                {testimonials.map((testimonial) => (
                                                                                                                                                                                                            <div
                                                                                                                                                                                                                          key={testimonial.name}
                                                                                                                                                                                                                                        className="bg-slate-900 border border-slate-800 rounded-2xl p-7"
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                  <div className="text-yellow-400 text-lg">
                                                                                                                                                                                                                                                                                  ★★★★★
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                              <p className="mt-5 text-slate-300 leading-relaxed">
                                                                                                                                                                                                                                                                                                                              "{testimonial.message}"
                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                          <div className="mt-6 flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                          <div className="w-11 h-11 rounded-full bg-cyan-500 flex items-center justify-center font-bold">
                                                                                                                                                                                                                                                                                                                                                                                            {testimonial.avatar}
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {testimonial.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {testimonial.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Testimonials;